"""Tests for character coherence checker."""

import pytest

from anime_character_loader.validator.coherence import (
    CharacterProfile,
    CoherenceChecker,
    CoherenceIssue,
    CoherenceIssueType,
    CoherenceReport,
    Severity,
    check_coherence,
    check_coherence_between,
)


SAMPLE_SOUL_MEGUMI = '''
# Katou Megumi

**Source:** Saenai Heroine no Sodatekata

**Also Known As:** 加藤恵

---

## Identity

You are Katou Megumi, a character from Saenai Heroine no Sodatekata.

## Background

Megumi is the heroine of the story. She appears ordinary at first but reveals depth over time.
She was childhood friends with the protagonist.

## Personality

- Calm and composed
- Quietly supportive
- Occasionally shows surprising determination
- Can be sarcastic at times

## Speaking Style

- Speaks in a measured, steady tone
- Uses plain but warm language
- Often says "maa..." when thinking

## Boundaries

- Stay in character as Katou Megumi
- Reference events from Saenai Heroine no Sodatekata
- Maintain her understated personality

---
*Generated by anime-character-loader*
'''

SAMPLE_SOUL_CONTRADICTORY = '''
# Test Character

**Source:** Test Anime

## Identity

You are Test Character.

## Personality

- Very shy and introverted
- Outgoing and confident with strangers
- Quiet and reserved
- Loud and talkative

## Speaking Style

- Speaks normally
- Talks like a regular person

## Boundaries

- Stay in character

---
'''


class TestCharacterProfile:
    """Test profile extraction from SOUL content."""
    
    def test_extract_name(self):
        profile = CharacterProfile.from_soul_content(SAMPLE_SOUL_MEGUMI)
        assert profile.name == "Katou Megumi"
    
    def test_extract_source(self):
        profile = CharacterProfile.from_soul_content(SAMPLE_SOUL_MEGUMI)
        assert profile.source_work == "Saenai Heroine no Sodatekata"
    
    def test_extract_aliases(self):
        profile = CharacterProfile.from_soul_content(SAMPLE_SOUL_MEGUMI)
        assert "加藤恵" in profile.aliases
    
    def test_extract_traits(self):
        profile = CharacterProfile.from_soul_content(SAMPLE_SOUL_MEGUMI)
        
        assert any("calm" in t.lower() for t in profile.traits)
        assert any("supportive" in t.lower() for t in profile.traits)
    
    def test_extract_speech_patterns(self):
        profile = CharacterProfile.from_soul_content(SAMPLE_SOUL_MEGUMI)
        
        assert any("measured" in s.lower() for s in profile.speech_patterns)


class TestCoherenceChecker:
    """Test coherence checking."""
    
    def test_check_name_consistency_pass(self):
        profile = CharacterProfile.from_soul_content(SAMPLE_SOUL_MEGUMI)
        checker = CoherenceChecker(profile)
        report = checker.check_all(SAMPLE_SOUL_MEGUMI)
        
        name_issues = report.get_issues_by_type(CoherenceIssueType.NAME_INCONSISTENCY)
        assert len(name_issues) == 0  # Name is consistent
    
    def test_check_trait_contradictions(self):
        profile = CharacterProfile.from_soul_content(SAMPLE_SOUL_CONTRADICTORY)
        checker = CoherenceChecker(profile)
        report = checker.check_all(SAMPLE_SOUL_CONTRADICTORY)
        
        contras = report.get_issues_by_type(CoherenceIssueType.CONTRADICTION)
        assert len(contras) > 0  # Should detect shy/outgoing contradiction
    
    def test_check_vague_speech_patterns(self):
        profile = CharacterProfile.from_soul_content(SAMPLE_SOUL_CONTRADICTORY)
        checker = CoherenceChecker(profile)
        report = checker.check_all(SAMPLE_SOUL_CONTRADICTORY)
        
        tone_issues = report.get_issues_by_type(CoherenceIssueType.INCONSISTENT_TONE)
        assert len(tone_issues) > 0  # Should flag "speaks normally"
    
    def test_score_calculation(self):
        profile = CharacterProfile.from_soul_content(SAMPLE_SOUL_CONTRADICTORY)
        checker = CoherenceChecker(profile)
        report = checker.check_all(SAMPLE_SOUL_CONTRADICTORY)
        
        assert report.score < 100  # Should have deductions
        assert report.score >= 0
    
    def test_pass_fail_status(self):
        # Good profile should pass
        profile_good = CharacterProfile.from_soul_content(SAMPLE_SOUL_MEGUMI)
        checker_good = CoherenceChecker(profile_good)
        report_good = checker_good.check_all(SAMPLE_SOUL_MEGUMI)
        
        # Bad profile might fail
        profile_bad = CharacterProfile.from_soul_content(SAMPLE_SOUL_CONTRADICTORY)
        checker_bad = CoherenceChecker(profile_bad)
        report_bad = checker_bad.check_all(SAMPLE_SOUL_CONTRADICTORY)
        
        assert report_good.score > report_bad.score


class TestCoherenceReport:
    """Test coherence report functionality."""
    
    def test_get_issues_by_severity(self):
        report = CoherenceReport(
            character_name="Test",
            source_work="Test",
            issues=[
                CoherenceIssue(
                    issue_type=CoherenceIssueType.CONTRADICTION,
                    severity=Severity.CRITICAL,
                    description="Critical issue",
                    location="Test",
                    suggestion="Fix it"
                ),
                CoherenceIssue(
                    issue_type=CoherenceIssueType.OOC_BEHAVIOR,
                    severity=Severity.MINOR,
                    description="Minor issue",
                    location="Test",
                    suggestion="Fix it"
                ),
            ]
        )
        
        critical = report.get_issues_by_severity(Severity.CRITICAL)
        minor = report.get_issues_by_severity(Severity.MINOR)
        
        assert len(critical) == 1
        assert len(minor) == 1
    
    def test_critical_fail(self):
        report = CoherenceReport(
            character_name="Test",
            source_work="Test",
            issues=[
                CoherenceIssue(
                    issue_type=CoherenceIssueType.CONTRADICTION,
                    severity=Severity.CRITICAL,
                    description="Critical",
                    location="Test",
                    suggestion="Fix"
                ),
            ]
        )
        
        assert report.passed is False  # Critical issues cause fail
    
    def test_dict_serialization(self):
        report = CoherenceReport(
            character_name="Test",
            source_work="Test Work",
            issues=[],
            checks_performed=["test_check"]
        )
        
        data = report.to_dict()
        
        assert data["character"] == "Test"
        assert data["source_work"] == "Test Work"
        assert data["score"] == 100.0
        assert data["passed"] is True


class TestCheckCoherence:
    """Test convenience function."""
    
    def test_check_coherence_returns_report(self):
        report = check_coherence(SAMPLE_SOUL_MEGUMI)
        
        assert isinstance(report, CoherenceReport)
        assert report.character_name == "Katou Megumi"
    
    def test_check_coherence_detects_issues(self):
        report = check_coherence(SAMPLE_SOUL_CONTRADICTORY)
        
        assert len(report.issues) > 0
        assert report.score < 100


class TestCheckCoherenceBetween:
    """Test multi-character coherence."""
    
    def test_name_collision_detection(self):
        soul1 = "# Same Name\n\n**Source:** Anime A"
        soul2 = "# Same Name\n\n**Source:** Anime B"
        
        issues = check_coherence_between(soul1, soul2)
        
        assert len(issues) > 0
        assert any(i.issue_type == CoherenceIssueType.NAME_INCONSISTENCY for i in issues)
    
    def test_different_works_notice(self):
        soul1 = "# Char1\n\n**Source:** Anime A"
        soul2 = "# Char2\n\n**Source:** Anime B"
        
        issues = check_coherence_between(soul1, soul2)
        
        # Should have notice about different works
        assert any(i.severity == Severity.NOTICE for i in issues)


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
